// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.6.1
// source: dnns.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DnnsPostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessKeyId     string `protobuf:"bytes,1,opt,name=AccessKeyId,proto3" json:"AccessKeyId,omitempty"`
	AccessKeySecret string `protobuf:"bytes,2,opt,name=AccessKeySecret,proto3" json:"AccessKeySecret,omitempty"`
	Endpoint        string `protobuf:"bytes,3,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	RecordId        string `protobuf:"bytes,4,opt,name=RecordId,proto3" json:"RecordId,omitempty"`
	RR              string `protobuf:"bytes,5,opt,name=RR,proto3" json:"RR,omitempty"`
	Type            string `protobuf:"bytes,6,opt,name=Type,proto3" json:"Type,omitempty"`
	Value           string `protobuf:"bytes,7,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *DnnsPostReq) Reset() {
	*x = DnnsPostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dnns_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DnnsPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnnsPostReq) ProtoMessage() {}

func (x *DnnsPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_dnns_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnnsPostReq.ProtoReflect.Descriptor instead.
func (*DnnsPostReq) Descriptor() ([]byte, []int) {
	return file_dnns_proto_rawDescGZIP(), []int{0}
}

func (x *DnnsPostReq) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *DnnsPostReq) GetAccessKeySecret() string {
	if x != nil {
		return x.AccessKeySecret
	}
	return ""
}

func (x *DnnsPostReq) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *DnnsPostReq) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *DnnsPostReq) GetRR() string {
	if x != nil {
		return x.RR
	}
	return ""
}

func (x *DnnsPostReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DnnsPostReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DnnsPostResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DnnsPostResp) Reset() {
	*x = DnnsPostResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dnns_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DnnsPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnnsPostResp) ProtoMessage() {}

func (x *DnnsPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_dnns_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnnsPostResp.ProtoReflect.Descriptor instead.
func (*DnnsPostResp) Descriptor() ([]byte, []int) {
	return file_dnns_proto_rawDescGZIP(), []int{1}
}

func (x *DnnsPostResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DnnsGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DnnsGetReq) Reset() {
	*x = DnnsGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dnns_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DnnsGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnnsGetReq) ProtoMessage() {}

func (x *DnnsGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_dnns_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnnsGetReq.ProtoReflect.Descriptor instead.
func (*DnnsGetReq) Descriptor() ([]byte, []int) {
	return file_dnns_proto_rawDescGZIP(), []int{2}
}

type DnnsGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data    string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DnnsGetResp) Reset() {
	*x = DnnsGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dnns_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DnnsGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnnsGetResp) ProtoMessage() {}

func (x *DnnsGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_dnns_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnnsGetResp.ProtoReflect.Descriptor instead.
func (*DnnsGetResp) Descriptor() ([]byte, []int) {
	return file_dnns_proto_rawDescGZIP(), []int{3}
}

func (x *DnnsGetResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DnnsGetResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_dnns_proto protoreflect.FileDescriptor

var file_dnns_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x6e, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xcb, 0x01, 0x0a, 0x0b, 0x64, 0x6e, 0x6e, 0x73, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65,
	0x79, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x52, 0x52, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x52, 0x52, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x28, 0x0a, 0x0c, 0x64, 0x6e, 0x6e, 0x73, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x64, 0x6e, 0x6e,
	0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x22, 0x3b, 0x0a, 0x0b, 0x64, 0x6e, 0x6e, 0x73, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x32, 0x96, 0x01, 0x0a, 0x04, 0x44, 0x6e, 0x6e, 0x73, 0x12, 0x49, 0x0a,
	0x08, 0x64, 0x6e, 0x6e, 0x73, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x64, 0x6e, 0x6e, 0x73, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x6e, 0x6e, 0x73, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x3a, 0x01, 0x2a, 0x22, 0x09, 0x2f,
	0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x07, 0x64, 0x6e, 0x6e, 0x73,
	0x47, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x6e, 0x6e, 0x73,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64,
	0x6e, 0x6e, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0b, 0x12, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x42, 0x1a, 0x5a,
	0x18, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d, 0x79,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_dnns_proto_rawDescOnce sync.Once
	file_dnns_proto_rawDescData = file_dnns_proto_rawDesc
)

func file_dnns_proto_rawDescGZIP() []byte {
	file_dnns_proto_rawDescOnce.Do(func() {
		file_dnns_proto_rawDescData = protoimpl.X.CompressGZIP(file_dnns_proto_rawDescData)
	})
	return file_dnns_proto_rawDescData
}

var file_dnns_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dnns_proto_goTypes = []interface{}{
	(*DnnsPostReq)(nil),  // 0: proto.dnnsPostReq
	(*DnnsPostResp)(nil), // 1: proto.dnnsPostResp
	(*DnnsGetReq)(nil),   // 2: proto.dnnsGetReq
	(*DnnsGetResp)(nil),  // 3: proto.dnnsGetResp
}
var file_dnns_proto_depIdxs = []int32{
	0, // 0: proto.Dnns.dnnsPost:input_type -> proto.dnnsPostReq
	2, // 1: proto.Dnns.dnnsGet:input_type -> proto.dnnsGetReq
	1, // 2: proto.Dnns.dnnsPost:output_type -> proto.dnnsPostResp
	3, // 3: proto.Dnns.dnnsGet:output_type -> proto.dnnsGetResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dnns_proto_init() }
func file_dnns_proto_init() {
	if File_dnns_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dnns_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DnnsPostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dnns_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DnnsPostResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dnns_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DnnsGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dnns_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DnnsGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dnns_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dnns_proto_goTypes,
		DependencyIndexes: file_dnns_proto_depIdxs,
		MessageInfos:      file_dnns_proto_msgTypes,
	}.Build()
	File_dnns_proto = out.File
	file_dnns_proto_rawDesc = nil
	file_dnns_proto_goTypes = nil
	file_dnns_proto_depIdxs = nil
}
